module.exports = {
  data: [
    "Be Careful Not To Choke On Your Convictions. ",
    "You saw what we did there right ?",
    "When I left you I was but the learner. Now I am the master. - Vader taunts Obi Wan, his Jedi teacher and a former friend just before he kills him. ",
    "The Force is strong with this one. Vader is commenting on the skills of an X - Wing pilot that is trying to blow up the Death Star, not realizing he's trying to kill his own son. ",
    "I am altering the deal, pray I do not alter it any further… – Vader tells Lando how it is from beneath his black helmet. Han is going with Boba Fett and everyone else is Vader's. ",
    "Impressive. Most impressive. Obi - Wan has taught you well. You have controlled your fear. Now, release your anger. Only your hatred can destroy me. – Vader praises Luke after he manages to escape Vader's trap with an acrobatic flip. ",
    "No, I am your father! – And so revealed was one of cinema's greatest plot twists that Vader was actually Luke's old man. ",
    "I hope so for your sake, the Emperor is not as forgiving as I am – This was the end of Vader's pep talk with the Jerjerrod who was in command of the second Death Star. ",
    "Give yourself to the Dark Side. It is the only way you can save your friends. Yes, your thoughts betray you. Your feelings for them are strong. Especially for… sister. So, you have a twin sister. ",
    "Your feelings have now betrayed her, too. Obi - Wan was wise to hide her from me. Now his failure is complete. If you will not turn to the Dark Side… then perhaps she will. . ",
    "I see through the lies of the Jedi. I do not fear the dark side as you do. I have brought peace, freedom, justice, and security to my new empire. ",
    "Just for once let me look on you with my own eyes… You were right. You were right about me. Tell your sister you were right. — Star Wars: Episode VI — Return of the Jedi",
    "Don't be too proud of this technological terror you've constructed. The ability to destroy a planet is insignificant next to the power of the Force… I find your lack of faith disturbing. — Star Wars: Episode IV — A New Hope",
    "I am altering the deal. Pray, I don't alter it any further. — Star Wars: Episode V — The Empire Strikes Back",
    "I see through the lies of the Jedi. I do not fear the dark side as you do. I have brought peace, freedom, justice, and security to my new empire. — Star Wars: Episode III — Revenge of the Sith",
    "I find your lack of faith disturbing. ",
    "Power!Unlimited power!",
    "You are a part of the Rebel Alliance and a traitor!",
    "From my point of view, the Jedi are evil. ",
    "What have I done ?",
    "Asteroids do not concern me, Admiral. ",
    "I have felt it. ",
    "He will join us or die!",
    "You don't know the power of the dark side. ",
    "I have you now. ",
    "Give into your hate and anger",
    "That name has no meaning",
    "You have failed me for the last time. ",
    "What is thy bidding my master. ",
    "Apology excepted. ",
    "I sense something. A presence I have not felt since…. (A New Hope) ",
    "This will be a day long remembered. It has seen the end of Kenobi; it will soon see the end of the Rebellion. (A New Hope) ",
    "I have you now. (A New Hope) ",
    "You have failed me for the last time, Admiral…. (The Empire Strikes Back) ",
    "What is thy bidding, my Master ? (The Empire Strikes Back) ",
    "He will join us or die, Master. (The Empire Strikes Back) ",
    "I do not want the Emperor's prize damaged. We will test it…on Captain Solo. (The Empire Strikes Back)",
    "If you only knew the power of the dark side. Obi - Wan never told you what happened to your father. ",
    "This technological terror is nothing compared to the power of the force",
    "Perhaps I can find new ways to motivate them. (Return of the Jedi) ",
    "I hope so for your sake, Commander. The Emperor is not as forgiving as I am. (Return of the Jedi) ",
    "The Emperor will show you the true nature of the Force. He is your Master now. (Return of the Jedi) ",
    "All I am surrounded by is fear, and dead men!",
    "Be careful not to choke on your aspirations, Director. – Star Wars Rogue One",
    "Just for once… let me… look on you with my OWN eyes",
    "Search your feelings, you know it to be true!",
    "If he could be turned, he would be a powerful ally. – Star Wars: Episode V – The Empire Strikes Back",
    "You are unwise to lower your defenses!"

  ]
}